version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    environment:
      DATABASE_HOST: postgres_container
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
    ports:
      - "5001:5001"
    networks:
      - app_network
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge